apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "erp-simulator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "erp-simulator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: erp-simulator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "erp-simulator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "erp-simulator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: erp-simulator
    spec:
      containers:
        - name: erp-simulator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: PYTHONUNBUFFERED
              value: "1"

            {{- if .Values.otel.enabled }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "{{ .Values.otel.endpoint }}"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_SERVICE_NAME
              value: "{{ .Values.otel.serviceName }}"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "{{ .Values.otel.resourceAttributes }}"
            {{- end }}

            - name: SIM_MEMORY_LEAK_ENABLED
              value: "{{ .Values.simulator.modes.memoryLeak }}"
            - name: SIM_CPU_SPIKE_ENABLED
              value: "{{ .Values.simulator.modes.cpuSpike }}"
            - name: SIM_LATENCY_JITTER_ENABLED
              value: "{{ .Values.simulator.modes.latencyJitter }}"
            - name: SIM_ERROR_BURST_ENABLED
              value: "{{ .Values.simulator.modes.errorBurst }}"
            - name: SIM_BASE_ERROR_RATE
              value: "{{ .Values.simulator.baseErrorRate }}"
            - name: SIM_MAX_EXTRA_LATENCY_MS
              value: "{{ .Values.simulator.maxExtraLatencyMs }}"

          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3

          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
