{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "erp-simulator.fullname" . }}
  labels:
    {{- include "erp-simulator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "erp-simulator.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
{{- end }}
